import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import styles from '@/app/layout.module.css';
import { ShoppingCart, Sidebar } from '@/components';
import Image from 'next/image';
import PlanetaImg from '@/components/Sidebar/planeta_zemlia_kosmos.png';
import CartProvider from '@/providers/CartProvider';

const inter = Inter({ subsets: ['latin'], weight: ['300', '400', '500', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
    <body className={inter.className} suppressHydrationWarning={true}>
    <CartProvider>
      <div className={styles.wrapper}>
        <Sidebar className={styles.sidebar}/>
        <div className={styles.img}>
          <Image src={PlanetaImg} alt="PlanetaImg"/>
        </div>
        <div className={styles.body}>
          {children}
        </div>
        <div className={styles.shoppingСart}>
          <CartProvider>
            <ShoppingCart/>
          </CartProvider>
        </div>
      </div>
    </CartProvider>
    </body>
    </html>
  );
}
